"""tweeters_perc_change

Revision ID: e86aad268247
Revises: 37121388a27b
Create Date: 2018-07-05 18:59:17.464633

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e86aad268247'
down_revision = '37121388a27b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('top_tweeters_1_new')
    op.drop_table('hash_activity_1_old')
    op.drop_table('dist_activity_7_old')
    op.drop_table('hash_activity_2_old')
    op.drop_table('dist_activity_28_old')
    op.drop_table('hash_activity_7_old')
    op.drop_table('dist_activity_2_old')
    op.drop_table('dist_activity_1_old')
    op.drop_table('hash_activity_28_old')
    op.alter_column('top_tweeters_1', 'user_cap_perc',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('top_tweeters_2', 'user_cap_perc',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('top_tweeters_28', 'user_cap_perc',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('top_tweeters_7', 'user_cap_perc',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('top_tweeters_7', 'user_cap_perc',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('top_tweeters_28', 'user_cap_perc',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('top_tweeters_2', 'user_cap_perc',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('top_tweeters_1', 'user_cap_perc',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.create_table('hash_activity_28_old',
    sa.Column('rank', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('hash_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('hashtag', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('rank'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('dist_activity_1_old',
    sa.Column('rank', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('district_name', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('rank'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('dist_activity_2_old',
    sa.Column('rank', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('district_name', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('rank'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('hash_activity_7_old',
    sa.Column('rank', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('hash_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('hashtag', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('rank'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('dist_activity_28_old',
    sa.Column('rank', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('district_name', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('rank'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('hash_activity_2_old',
    sa.Column('rank', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('hash_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('hashtag', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('rank'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('dist_activity_7_old',
    sa.Column('rank', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('district_name', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('rank'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('hash_activity_1_old',
    sa.Column('rank', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('hash_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('hashtag', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('rank'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('top_tweeters_1_new',
    sa.Column('rank', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('user_scrname', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('user_cap_perc', mysql.FLOAT(), nullable=False),
    sa.Column('count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('rank'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
